name1 = input(" Hello, What is your name? ")
print(f"Hello {name1}, nice to meet you! My name is Julia")
ENTER = input(" I want to get to know you more, can I ask you some questions? If so click ENTER 2 times...")
input()
print(" Thanks for clicking I can't wait.")
color = input(" What is your favorite color? ")
print(f" I Love the color {color}! Click enter for another question...")
input()
pets = input(" Do you have any pets? If so what animal? TYPE ONLY THE ANIMAL... ")
input()
print(f" I love {pets}s! I have one of my own.")
name = input("What is their name? ")
input()
print(f" My pet is also named {name}! What a coincidence!")
input()
print(" Lets talk about today.")
input()
feel = input(" How do you feel today? ")
input()
print(f" Interesting I felt {feel} yesterday.")
print(f" {name1}, {feel} can be a weird feeling. ")
input()
print(" Now let's change subject, now ask me a yes or no question!")
input()
input(" Yes.")
print(" Ask me just one more! ")
input()
input(" Thats a hard one i'll have to say no.")
input()
print(" Its been great talking to you farewell!")